// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwineBot.Model;

#nullable disable

namespace SwineBot.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260404201201_private_fluent")]
    partial class private_fluent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SwineBot.Model.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwineInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("AchievementId");

                    b.HasIndex("SwineInfoId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("SwineBot.Model.DuelRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestId");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.ToTable("DuelRequests");
                });

            modelBuilder.Entity("SwineBot.Model.DuelResult", b =>
                {
                    b.Property<int>("DuelResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttackerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttackerWon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefenderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoserWeightAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoserWeightBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerWeightAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerWeightBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("DuelResultId");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.ToTable("DuelResults");
                });

            modelBuilder.Entity("SwineBot.Model.Feed", b =>
                {
                    b.Property<int>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeedId");

                    b.HasIndex("SwineId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("SwineBot.Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SwineBot.Model.Slaughter", b =>
                {
                    b.Property<int>("SlaughterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SwineName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwineWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SlaughterId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Slaughters");
                });

            modelBuilder.Entity("SwineBot.Model.Swine", b =>
                {
                    b.Property<int>("SwineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("SwineId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Swines");
                });

            modelBuilder.Entity("SwineBot.Model.SwineInfo", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfoId");

                    b.HasIndex("SwineId")
                        .IsUnique();

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("SwineBot.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrivateSwineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("PrivateSwineId")
                        .IsUnique();

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwineBot.Model.WeightLoss", b =>
                {
                    b.Property<int>("LossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsThrowUp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LossId");

                    b.HasIndex("SwineId");

                    b.ToTable("WeightLosses");
                });

            modelBuilder.Entity("SwineBot.Model.Achievement", b =>
                {
                    b.HasOne("SwineBot.Model.SwineInfo", null)
                        .WithMany()
                        .HasForeignKey("SwineInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwineBot.Model.DuelRequest", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwineBot.Model.DuelResult", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwineBot.Model.Feed", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithMany()
                        .HasForeignKey("SwineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwineBot.Model.Slaughter", b =>
                {
                    b.HasOne("SwineBot.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwineBot.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwineBot.Model.Swine", b =>
                {
                    b.HasOne("SwineBot.Model.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwineBot.Model.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwineBot.Model.SwineInfo", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithOne()
                        .HasForeignKey("SwineBot.Model.SwineInfo", "SwineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwineBot.Model.User", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithOne()
                        .HasForeignKey("SwineBot.Model.User", "PrivateSwineId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SwineBot.Model.WeightLoss", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", null)
                        .WithMany()
                        .HasForeignKey("SwineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
