// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwineBot.Model;

#nullable disable

namespace SwineBot.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20260322213903_Rename Stats to Info")]
    partial class RenameStatstoInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SwineBot.Model.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwineInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("AchievementId");

                    b.HasIndex("SwineInfoId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("SwineBot.Model.DuelRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestId");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.ToTable("DuelRequests");
                });

            modelBuilder.Entity("SwineBot.Model.DuelResult", b =>
                {
                    b.Property<int>("DuelResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttackerWon")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefenderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoserWeightAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoserWeightBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerSwineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerWeightAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinnerWeightBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("DuelResultId");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.HasIndex("WinnerSwineId");

                    b.ToTable("DuelResults");
                });

            modelBuilder.Entity("SwineBot.Model.Feed", b =>
                {
                    b.Property<int>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeedId");

                    b.HasIndex("SwineId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("SwineBot.Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SwineBot.Model.Slaughter", b =>
                {
                    b.Property<int>("SlaughterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SwineName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwineWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SlaughterId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Slaughters");
                });

            modelBuilder.Entity("SwineBot.Model.Swine", b =>
                {
                    b.Property<int>("SwineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("SwineId");

                    b.HasIndex("GroupId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Swines");
                });

            modelBuilder.Entity("SwineBot.Model.SwineInfo", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfoId");

                    b.HasIndex("SwineId")
                        .IsUnique();

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("SwineBot.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwineBot.Model.WeightLoss", b =>
                {
                    b.Property<int>("LossId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsThrowUp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LossId");

                    b.HasIndex("SwineId");

                    b.ToTable("WeightLosses");
                });

            modelBuilder.Entity("SwineBot.Model.Achievement", b =>
                {
                    b.HasOne("SwineBot.Model.SwineInfo", "SwineInfo")
                        .WithMany("Achievements")
                        .HasForeignKey("SwineInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwineInfo");
                });

            modelBuilder.Entity("SwineBot.Model.DuelRequest", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwineBot.Model.Swine", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attacker");

                    b.Navigation("Defender");
                });

            modelBuilder.Entity("SwineBot.Model.DuelResult", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwineBot.Model.Swine", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwineBot.Model.Swine", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerSwineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Attacker");

                    b.Navigation("Defender");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("SwineBot.Model.Feed", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", "Swine")
                        .WithMany("Feeds")
                        .HasForeignKey("SwineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Swine");
                });

            modelBuilder.Entity("SwineBot.Model.Slaughter", b =>
                {
                    b.HasOne("SwineBot.Model.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SwineBot.Model.User", "User")
                        .WithMany("Slaughters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SwineBot.Model.Swine", b =>
                {
                    b.HasOne("SwineBot.Model.Group", "Group")
                        .WithMany("Swines")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwineBot.Model.User", "Owner")
                        .WithMany("Swines")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SwineBot.Model.SwineInfo", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", "Swine")
                        .WithOne("Info")
                        .HasForeignKey("SwineBot.Model.SwineInfo", "SwineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Swine");
                });

            modelBuilder.Entity("SwineBot.Model.WeightLoss", b =>
                {
                    b.HasOne("SwineBot.Model.Swine", "Swine")
                        .WithMany("WeightLosses")
                        .HasForeignKey("SwineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Swine");
                });

            modelBuilder.Entity("SwineBot.Model.Group", b =>
                {
                    b.Navigation("Swines");
                });

            modelBuilder.Entity("SwineBot.Model.Swine", b =>
                {
                    b.Navigation("Feeds");

                    b.Navigation("Info");

                    b.Navigation("WeightLosses");
                });

            modelBuilder.Entity("SwineBot.Model.SwineInfo", b =>
                {
                    b.Navigation("Achievements");
                });

            modelBuilder.Entity("SwineBot.Model.User", b =>
                {
                    b.Navigation("Slaughters");

                    b.Navigation("Swines");
                });
#pragma warning restore 612, 618
        }
    }
}
